# NumPy Exercises

## 1. Convert List to NumPy Array

**Question:** Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.

**Expected Output:**

*Original List:* [12.23, 13.32, 100, 36.32] 
*One-dimensional numpy array:* [ 12.23 13.32 100. 36.32]


In [4]:
import numpy as np

In [5]:
number_list = [12.23, 13.32, 100, 36.32] 
print(f'orignal List: {number_list}')
print(f'1D numpy array: {np.array(number_list)}')


orignal List: [12.23, 13.32, 100, 36.32]
1D numpy array: [ 12.23  13.32 100.    36.32]


## 2. Create 3x3 Matrix

**Question:** Create a 3x3 matrix with values ranging from 2 to 10.

**Expected Output:**
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [6]:
np.arange(2,11).reshape((3,3))

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

## 3. Null Vector with Update

**Question:** Write a Python program to create a null vector of size 10 and update the sixth value to 11.

**Expected Output:**
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [7]:
vector = np.zeros(10)
vector[6] = 11
vector


array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

## 4. Reverse an Array

**Question:** Write a Python program to reverse an array (first element becomes last).

**Expected Output:**
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [8]:
array = np.arange(12,38)
print(f'before reverse: {array}')
print(f'after reverse: {array[::-1]}')

before reverse: [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
after reverse: [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


## 5. 2D Array with Border

**Question:** Write a Python program to create a 2D array with 1 on the border and 0 inside.

**Expected Output:**
Original array:
[[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]]

1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 1. 1. 1. 1.]]

In [9]:
matrix = np.ones((5,5))
print(f'before reverse: \n{matrix}')
matrix[1:4:,1:4] = 0
print(f'after reverse: \n{matrix}')

before reverse: 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
after reverse: 
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## 6. Add Border Around Array

**Question:** Write a Python program to add a border (filled with 0's) around an existing array.

**Expected Output:**
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 0. 0. 0. 0.]]

In [10]:
matrix = np.ones((3,3))
print(f'before border: \n{matrix}')
bordered_matrix = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(f'after border: \n{bordered_matrix}')


before border: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
after border: 
[ 0 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37  0]


## 7. Checkerboard Pattern

**Question:** Write a Python program to create an 8x8 matrix and fill it with a checkerboard pattern.

**Expected Output:**
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]



In [11]:
n = 8
matrix = np.zeros((n, n), dtype=int)

mask = np.indices((n, n)).sum(axis=0) % 2

matrix[:] = mask

print("Checkerboard pattern:")
print(matrix)


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 8. Convert List and Tuple to Arrays

**Question:** Write a Python program to convert a list and tuple into arrays.

**Expected Output:**
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]

In [12]:
python_list = [1,2,3,4,5,6,7,8,9]
touple = [(8, 4, 6),(1, 2, 3)]
np.array(touple)

array([[8, 4, 6],
       [1, 2, 3]])

## 9. Append Values to Array

**Question:** Write a Python program to append values to the end of an array.

**Expected Output:**
Original array:
[10, 20, 30]

After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [13]:
original_array = np.arange(10,40,10)
values_to_append = np.arange(30,100,10)
print(f'original array: {original_array}')
print(f'values to append: {values_to_append}')
print(f'output: {np.append(original_array,values_to_append)}')

original array: [10 20 30]
values to append: [30 40 50 60 70 80 90]
output: [10 20 30 30 40 50 60 70 80 90]


## 10. Real and Imaginary Parts of Array

**Question:** Write a Python program to find the real and imaginary parts of an array of complex numbers.

**Expected Output:**
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]
Real part of the array:
[ 1. 0.70710678]
Imaginary part of the array:
[ 0. 0.70710678]

In [14]:
complex_array = np.array([1.00000000 + 0.j, 0.70710678 + 0.70710678j])

real_part = complex_array.real

imaginary_part = complex_array.imag

print("Original array:")
print(complex_array)

print("\nReal part of the array:")
print(real_part)

print("\nImaginary part of the array:")
print(imaginary_part)


Original array:
[1.        +0.j         0.70710678+0.70710678j]

Real part of the array:
[1.         0.70710678]

Imaginary part of the array:
[0.         0.70710678]


## 11. Array Size and Memory Usage

**Question:** Write a Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

**Expected Output:**
Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24

In [15]:
array = np.array([10, 20, 30], dtype=np.float64)

array_size = array.size

element_size = array.itemsize

total_bytes = array.nbytes

print("Size of the array:", array_size)
print("Length of one array element in bytes:", element_size)
print("Total bytes consumed by the elements of the array:", total_bytes)


Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24


## 12. Common Values Between Two Arrays

**Question:** Write a Python program to find common values between two arrays.

**Expected Output:**
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]

In [16]:
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([10, 30, 40])

common_values = np.intersect1d(array1, array2)

print("Array1:", array1)
print("Array2:", array2)

print("\nCommon values between two arrays:")
print(common_values)

Array1: [ 0 10 20 40 60]
Array2: [10 30 40]

Common values between two arrays:
[10 40]


## 13. Set Difference of Two Arrays

**Question:** Write a Python program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.

**Expected Output:**
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays:
[ 0 20 60 80]

In [17]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70, 90])

set_difference = np.setdiff1d(array1, array2)

print("Array1:", array1)
print("Array2:", array2)

print("\nSet difference between two arrays:")
print(set_difference)


Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70 90]

Set difference between two arrays:
[ 0 20 60 80]


## 14. Set Exclusive-Or of Two Arrays

**Question:** Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.

**Expected Output:**
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]

In [18]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])

exclusive_or = np.setxor1d(array1, array2)

print("Array1:", array1)
print("Array2:", array2)

print("\nUnique values that are in only one (not both) of the input arrays:")
print(exclusive_or)


Array1: [ 0 10 20 40 60 80]
Array2: [10 30 40 50 70]

Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


## 15. Compare Two Arrays

**Question:** Write a Python program to compare two arrays using numpy.

**Expected Output:**
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]

In [19]:
a = np.array([1, 2])
b = np.array([4, 5])

print(f'a: {a}')
print(f'b: {b}')
print(f'a>b: {a>b}')
print(f'a>=b: {a>=b}')
print(f'a<b: {a<b}')
print(f'a<=b: {a<=b}')

a: [1 2]
b: [4 5]
a>b: [False False]
a>=b: [False False]
a<b: [ True  True]
a<=b: [ True  True]


## 16. Save NumPy Array to a Text File

**Question:** Write a Python program to save a NumPy array to a text file.


In [20]:
array = np.arange(1,10)
array.tofile('array_data.csv', sep=',', format='%d')

## 17. Create Contiguous Flattened Array

**Question:** Write a Python program to create a contiguous flattened array.

**Expected Output:**
Original array:
[[10 20 30]
[20 40 50]]
New flattened array:
[10 20 30 20 40 50]

In [21]:
array = np.arange(9).reshape((3,3))
print(f'original array: {array}')
print(f'flattend array: {array.ravel()}')


original array: [[0 1 2]
 [3 4 5]
 [6 7 8]]
flattend array: [0 1 2 3 4 5 6 7 8]


## 18. 3D Array with Diagonal Ones

**Question:** Write a Python program to create a 3-D array with ones on a diagonal and zeros elsewhere.

**Expected Output:**
[[ 1. 0. 0.]
[ 0. 1. 0.]
[ 0. 0. 1.]]

In [22]:
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## 19. Create Specific Array

**Question:** Write a Python program to create an array which looks like below array.

**Expected Output:**
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]
[ 1. 1. 1.]]

In [26]:
np.tri(4, 3, -1, dtype=float)

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

## 20. Concatenate Two 2D Arrays

**Question:** Write a Python program to concatenate two 2-dimensional arrays.

**Expected Output:**
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]])
Expected Output:
[[ 0 1 3 0 2 4]
[ 5 7 9 6 8 10]]

In [28]:
array1 = np.array([[0, 1, 3],
                   [5, 7, 9]])

array2 = np.array([[0, 2, 4],
                   [6, 8, 10]])

np.concatenate((array1, array2), axis=1)

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

## 21. Make Array Immutable

**Question:** Write a Python program to make an array immutable (read-only).

**Expected Output:**
Test the array is read-only or not:
Try to change the value of the first element:
Traceback (most recent call last):
File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in
x[0] = 1
ValueError: assignment destination is read-only

In [29]:
array = np.array([1, 2, 3, 4, 5])

array.flags.writeable = False

print("Original array:", array)

try:
    array[0] = 10
except ValueError as e:
    print("Error:", e)


Original array: [1 2 3 4 5]
Error: assignment destination is read-only


## 22. Multiply Array Elements

**Question:** Write a Python program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array.

**Expected Output:**
Original array elements:
[[ 0 1 2 3]
[ 4 5 6 7]
[ 8 9 10 11]]
New array elements:
[[ 0 3 6 9]
[12 15 18 21]
[24 27 30 33]]



In [31]:
array = np.arange(9).reshape((3,3))

print("Original array elements:")
print(array)

new_array = array * 3

print("\nNew array elements:")
print(new_array)


Original array elements:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

New array elements:
[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]


## 23. Convert NumPy Array to Python List

**Question:** Write a Python program to convert a NumPy array into Python list structure.

**Expected Output:**
Original array elements:
[[0 1]
[2 3]
[4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]

In [32]:
import numpy as np

array = np.arange(6).reshape((3,2))

print("Original array elements:")
print(array)

list_structure = array.tolist()

print("\nArray to list:")
print(list_structure)
 

Original array elements:
[[0 1]
 [2 3]
 [4 5]]

Array to list:
[[0, 1], [2, 3], [4, 5]]


## 24. Print Array with Precision

**Question:** Write a Python program to convert a NumPy array into Python list structure with precision.

**Expected Output:**
Original array elements:
[ 0.26153123 0.52760141 0.5718299 0.5927067 0.7831874 0.69746349
0.35399976 0.99469633 0.0694458 0.54711478]
Print array values with precision 3:
[ 0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]

In [37]:
array = np.linspace(0,1)

print("Original array elements:")
print(array)

np.set_printoptions(precision=3)
print("\nPrint array values with precision 3:")
print(array)

Original array elements:
[0.    0.02  0.041 0.061 0.082 0.102 0.122 0.143 0.163 0.184 0.204 0.224
 0.245 0.265 0.286 0.306 0.327 0.347 0.367 0.388 0.408 0.429 0.449 0.469
 0.49  0.51  0.531 0.551 0.571 0.592 0.612 0.633 0.653 0.673 0.694 0.714
 0.735 0.755 0.776 0.796 0.816 0.837 0.857 0.878 0.898 0.918 0.939 0.959
 0.98  1.   ]

Print array values with precision 3:
[0.    0.02  0.041 0.061 0.082 0.102 0.122 0.143 0.163 0.184 0.204 0.224
 0.245 0.265 0.286 0.306 0.327 0.347 0.367 0.388 0.408 0.429 0.449 0.469
 0.49  0.51  0.531 0.551 0.571 0.592 0.612 0.633 0.653 0.673 0.694 0.714
 0.735 0.755 0.776 0.796 0.816 0.837 0.857 0.878 0.898 0.918 0.939 0.959
 0.98  1.   ]


## 25. Suppress Scientific Notation

**Question:** Write a Python program to suppress the use of scientific notation for small numbers in NumPy array.

**Expected Output:**
Original array elements:
[ 1.60000000e-10 1.60000000e+00 1.20000000e+03 2.35000000e-01]
Print array values with precision 3:
[ 0. 1.6 1200. 0.235]



## 26. Add Extra Column to Array

**Question:** Write a Python program to add an extra column to a NumPy array.

**Expected Output:**
[[ 10 20 30 100]
[ 40 50 60 200]]


## 27. Remove Specific Elements

**Question:** Write a Python program to remove specific elements in a NumPy array.

**Expected Output:**
Original array:
[ 10 20 30 40 50 60 70 80 90 100]
Delete first, fourth and fifth elements:
[ 20 30 60 70 80 90 100]